### ISSUE TITLE
Error: connect EHOSTUNREACH 

### ISSUE THREAD

**Issue by Caban-ru** [waynehaffenden/node-red-contrib-bravia#11]
I use "GetPowerStatus" every 10 seconds
and sometimes instead of the status I get this error
"Error: connect EHOSTUNREACH 192.168.100.6: 80"
Both devices are nearby and connected by a 100Mbit wire, so I don't think it's a network problem. Apparently Andoid tv sometimes does not have time to process the request? Is there any way to increase the waiting time for a response?

**Comment by waynehaffenden** [comment]
I'll be honest, I have no access to a node red setup or access to a Sony TV anymore so this project is basically dead. However, I've released a new version which should allow you to pass a timeout in milliseconds (defaults to 5 seconds) via the TV config option but have no way to test so this may sadly achieve nothing.

You're welcome to do a pull request and I'll accept. Hope you get it working :)
