### ISSUE TITLE
Sony BRAVIA device discovery failed

### ISSUE THREAD

**Issue by ClimbThatApple** [waynehaffenden/node-red-contrib-bravia#12]
I am having trouble adding my TV to this node. I have entered 20060 as the port as specified on Sonys website for TCP control and have created a Pre-shared key on the TV. For the Host I have tried both the IP address of the TV and the MAC address and both result in an immediate error message when I select the search icon "Sony BRAVIA device discovery failed". Additionally, if I just try to manually save the connection using the IP address or MAC address as the host, when I search for the IRCC code, I get an error message saying "Cannot get IRCC Codes, Check Connection with TV"

Any ideas on what I may be doing wrong to connect the TV to the node? I have gone through and turned on all the necessary settings and dug through the menu to see if there was anything I was missing, but I can't seem to figure anything out. Any help would be appreciated

**Comment by waynehaffenden** [comment]
The first thing I would try is to see if you can access the TV's IP address/port via something like curl or a web browser, if you can access then that rules out any networking or firewall issues.

**Comment by ClimbThatApple** [comment]
Hi wwaynehaffenden, thanks for the reply. I have been successful in issuing POST requests to the TV through Sonys Display Controller site and through the HTTP node. I might be able to figure out how to do what I need with just the HTTP request node but the Bravia node would be super convenient.

**Comment by waynehaffenden** [comment]
It sounds like the underlying library that this module uses no longer works. Unfortunately, I no longer have access to a Sony Bravia TV and therefore unable to test. You're welcome to look into this and add a pull request though, happy to assist wherever possible.

**Comment by ClimbThatApple** [comment]
I was ablate get everything to work through just API requests. I spent the past two days tinkering around with the API and setting everything up how I want it, but I woke up this morning to a bunch of 404 not found errors and Im not sure why. Even the displaycontrol.html is giving me a 404 error. You mentioned something about network or firewall issues, any ideas what could've happen between when it was working and now isn't?

**Comment by waynehaffenden** [comment]
How odd, honestly, I'm really not sure - a 404 error is a not found error, so sounds less like a firework/network issue. Have you tried a fresh install of node red? How are you running node red?

**Comment by ClimbThatApple** [comment]
I don't think its a node-red issue as the 404 errors are happening on Sonys DisplayControl.html site as well. According to the API documentation a 404 error is "For cases where the request is not matched to any supported API version." but I didn't change API versions overnight so I have no idea what happened.

**Comment by ClimbThatApple** [comment]
Hey waynehaffenden! Turns out the TV just needed to be rebooted! Everything is working perfectly now! I really appreciate you replying and helping me out even though you don't have a Bravia anymore! You're the man! For those interested, Sonys API documentation is really good: https://pro-bravia.sony.net/develop/integrate/rest-api/spec/

**Comment by waynehaffenden** [comment]
Ah I would have never had guessed, I don't think I helped much but I'm so glad you sorted it. At least if someone else has the same issue this could save them a lot of time!
