### ISSUE TITLE
Start VideoLAN

### ISSUE THREAD

**Issue by Barabba11** [waynehaffenden/node-red-contrib-bravia#13]
Hi mates, please forgive me to open an issue to ask a question, is it possible to start VLC opening a particular rtsp link? Thank you a lot

**Comment by waynehaffenden** [comment]
Hi @Barabba11, sadly, I'm not sure whether this is possible or not as I no longer have access to a Sony Bravia TV. Please check their documentation here [https://pro-bravia.sony.net/develop/integrate/rest-api/spec/](https://pro-bravia.sony.net/develop/integrate/rest-api/spec/) as this might help

**Comment by Barabba11** [comment]
thank you for your kind message :) I suppose it's better to ask somebody who knows well this tricks.. if there is a way to create an icon on TV to start VLAN with an rtsp and/or do it with IP.. do you know an active forum about Bravia? Thnak you a lot!

**Comment by waynehaffenden** [comment]
Sadly, again I don't have any knowledge on any of this I'm afraid. Sorry I can't help

**Comment by Barabba11** [comment]
Hi! Let me please ask another question, I've searched in the doc you sent me but can't find a way to launch another app there, but in your list there are "PartnerApp1" and so on, how they can be useful?
Thank you
