### ISSUE TITLE
How to open a particular Youtube video using IRCC?

### ISSUE THREAD

**Issue by Barabba11** [waynehaffenden/node-red-contrib-bravia#15]
Hi mate, sorry to open an issue for a question, I would like to start my tv playing a fireplace, for example this;
https://www.youtube.com/watch?v=AWKzr6n0ea0

Do you know how can I use your module to start it? What to type in your module exactly? I tried to figure it out around but seems difficult. Thank you a lot!

**Comment by Barabba11** [comment]
Any possible way to do that? I've read it's possible to open a custom app, maybe a link. If there is a chance to create a link that will open a particular video..

**Comment by waynehaffenden** [comment]
@Barabba11 I'm really sorry but I'm no longer working on this project or have any access to a Bravia TV anymore to help :( I hope you manage to find a solution.

**Comment by Barabba11** [comment]
thanks, sorry (
