### ISSUE TITLE
can't get setPowerStatus to work

### ISSUE THREAD

**Issue by vacquah** [waynehaffenden/node-red-contrib-bravia#17]
I am looking to put my tv in active or standby status using the setPowerStatus using` {"status":"active"} or {status":"standby"} ` for the payload. I can't get it to work. Please see the screenshots below.  I have tried plugging in the payload in the payload box or through the inject node ( as a json string).  Still doesn't work. Thxx.

![tv1](https://user-images.githubusercontent.com/2125909/153314842-652a4224-e111-4557-9357-3a41387486f5.jpg)

and 

![tv2](https://user-images.githubusercontent.com/2125909/153314864-4301a3b0-39d5-4f3c-8b7f-3a6eb6134f96.jpg)

**Comment by waynehaffenden** [comment]
@vacquah Try sending `{"status":"true"}` or `{"status":"false"}`

**Comment by vacquah** [comment]
> @vacquah Try sending `{"status":"true"}` or `{"status":"false"}`

same result i both within the node or injecting it from the in inject node.

![tv3](https://user-images.githubusercontent.com/2125909/153488548-f4d0fcb8-e5c4-4c97-8b0f-7019bec32d6f.jpg)

**Comment by vacquah** [comment]
> @vacquah Try sending `{"status":"true"}` or `{"status":"false"}`

Thank you. Rather this worked -  `{"status":true}`
