### ISSUE TITLE
Unexpected token after installation

### ISSUE THREAD

**Issue by DotOnedotNL** [waynehaffenden/node-red-contrib-bravia#4]
After installation the registration of the node throws an error:

Installing module: node-red-contrib-bravia, version: 1.1.2
Installed module: node-red-contrib-bravia
Added node types:
 - node-red-contrib-bravia:bravia-api : SyntaxError: Unexpected token = (line:3)
 - node-red-contrib-bravia:bravia-ircc : SyntaxError: Unexpected token = (line:3)
 - node-red-contrib-bravia:bravia-tv : SyntaxError: Unexpected token = (line:3)

**Comment by waynehaffenden** [comment]
What version of node.js do you have installed on the server running Node-RED as this package requires a minimum version of 5.0.0?

**Comment by DotOnedotNL** [comment]
Ahh, that's it. This was still a default installation on Ubuntu 16.04. Hence 4.2.6.
All ok after upgrading. Thnx
